/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Usuario
 */
public class frmPrincipal3 extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal3
     */
    public frmPrincipal3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorHeader = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        headerLogoNombre = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        headerUsuarioSesion = new javax.swing.JPanel();
        preferencias = new javax.swing.JPanel();
        lblMisPreferencias = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        iconUser = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        nameUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        perfilUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Nav = new javax.swing.JPanel();
        ContMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnProyectos = new javax.swing.JButton();
        btnPresupuestos = new javax.swing.JButton();
        btnPartidas = new javax.swing.JButton();
        btnPlanillas = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ContenedorBody = new javax.swing.JPanel();
        Body = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        footer = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setPreferredSize(new java.awt.Dimension(1200, 720));

        ContenedorHeader.setOpaque(false);
        ContenedorHeader.setPreferredSize(new java.awt.Dimension(842, 68));
        ContenedorHeader.setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(51, 51, 51));
        Header.setPreferredSize(new java.awt.Dimension(842, 38));
        Header.setLayout(new java.awt.BorderLayout());

        headerLogoNombre.setOpaque(false);
        headerLogoNombre.setPreferredSize(new java.awt.Dimension(450, 38));
        headerLogoNombre.setLayout(new java.awt.BorderLayout());

        Logo.setOpaque(false);
        Logo.setPreferredSize(new java.awt.Dimension(48, 38));

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        headerLogoNombre.add(Logo, java.awt.BorderLayout.LINE_START);

        Titulo.setOpaque(false);
        Titulo.setPreferredSize(new java.awt.Dimension(402, 38));
        Titulo.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Sistema de Control de Agua y Saneamiento");
        Titulo.add(jLabel3, java.awt.BorderLayout.CENTER);

        headerLogoNombre.add(Titulo, java.awt.BorderLayout.CENTER);

        Header.add(headerLogoNombre, java.awt.BorderLayout.LINE_START);

        headerUsuarioSesion.setOpaque(false);
        headerUsuarioSesion.setPreferredSize(new java.awt.Dimension(490, 38));
        headerUsuarioSesion.setLayout(new java.awt.BorderLayout());

        preferencias.setOpaque(false);

        lblMisPreferencias.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblMisPreferencias.setForeground(new java.awt.Color(255, 255, 255));
        lblMisPreferencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMisPreferencias.setText("Mis Preferencias");

        javax.swing.GroupLayout preferenciasLayout = new javax.swing.GroupLayout(preferencias);
        preferencias.setLayout(preferenciasLayout);
        preferenciasLayout.setHorizontalGroup(
            preferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(preferenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMisPreferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        preferenciasLayout.setVerticalGroup(
            preferenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMisPreferencias, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        headerUsuarioSesion.add(preferencias, java.awt.BorderLayout.LINE_START);

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setOpaque(false);

        btnCerrarSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setAlignmentY(0.0F);
        btnCerrarSesion.setMinimumSize(new java.awt.Dimension(97, 23));
        btnCerrarSesion.setOpaque(false);
        btnCerrarSesion.setPreferredSize(new java.awt.Dimension(97, 23));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        headerUsuarioSesion.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 38));
        jPanel8.setLayout(new java.awt.BorderLayout());

        iconUser.setOpaque(false);
        iconUser.setPreferredSize(new java.awt.Dimension(38, 38));

        javax.swing.GroupLayout iconUserLayout = new javax.swing.GroupLayout(iconUser);
        iconUser.setLayout(iconUserLayout);
        iconUserLayout.setHorizontalGroup(
            iconUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );
        iconUserLayout.setVerticalGroup(
            iconUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel8.add(iconUser, java.awt.BorderLayout.LINE_START);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(163, 38));
        jPanel3.setLayout(new java.awt.BorderLayout());

        nameUser.setOpaque(false);
        nameUser.setPreferredSize(new java.awt.Dimension(143, 20));
        nameUser.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Miguel Mosquera");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setPreferredSize(new java.awt.Dimension(90, 15));
        nameUser.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.add(nameUser, java.awt.BorderLayout.PAGE_START);

        perfilUser.setOpaque(false);
        perfilUser.setPreferredSize(new java.awt.Dimension(183, 18));
        perfilUser.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrador");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        perfilUser.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel3.add(perfilUser, java.awt.BorderLayout.PAGE_END);

        jPanel8.add(jPanel3, java.awt.BorderLayout.CENTER);

        headerUsuarioSesion.add(jPanel8, java.awt.BorderLayout.CENTER);

        Header.add(headerUsuarioSesion, java.awt.BorderLayout.LINE_END);

        ContenedorHeader.add(Header, java.awt.BorderLayout.PAGE_START);

        Nav.setBackground(new java.awt.Color(204, 204, 204));
        Nav.setPreferredSize(new java.awt.Dimension(842, 30));
        Nav.setLayout(new java.awt.BorderLayout());

        ContMenu.setOpaque(false);
        ContMenu.setPreferredSize(new java.awt.Dimension(760, 38));
        ContMenu.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(752, 30));
        jPanel1.setLayout(new java.awt.GridLayout());

        btnProyectos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProyectos.setText("Proyectos");
        btnProyectos.setOpaque(false);
        jPanel1.add(btnProyectos);

        btnPresupuestos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPresupuestos.setText("Presupuestos");
        btnPresupuestos.setOpaque(false);
        jPanel1.add(btnPresupuestos);

        btnPartidas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPartidas.setText("Partidas");
        btnPartidas.setOpaque(false);
        jPanel1.add(btnPartidas);

        btnPlanillas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPlanillas.setText("Planillas");
        btnPlanillas.setOpaque(false);
        jPanel1.add(btnPlanillas);

        btnReportes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setOpaque(false);
        jPanel1.add(btnReportes);

        btnUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setOpaque(false);
        jPanel1.add(btnUsuarios);

        ContMenu.add(jPanel1, java.awt.BorderLayout.LINE_START);

        Nav.add(ContMenu, java.awt.BorderLayout.LINE_START);

        jPanel5.setOpaque(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Fecha: 27/02/2013");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        Nav.add(jPanel5, java.awt.BorderLayout.LINE_END);

        ContenedorHeader.add(Nav, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(ContenedorHeader, java.awt.BorderLayout.PAGE_START);

        ContenedorBody.setOpaque(false);
        ContenedorBody.setPreferredSize(new java.awt.Dimension(842, 336));
        ContenedorBody.setLayout(new java.awt.BorderLayout());

        Body.setOpaque(false);
        Body.setPreferredSize(new java.awt.Dimension(842, 480));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Cuadro de Mandos", jPanel4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Espacio de Trabajo", jPanel6);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        ContenedorBody.add(Body, java.awt.BorderLayout.PAGE_START);

        footer.setBackground(new java.awt.Color(102, 102, 102));
        footer.setPreferredSize(new java.awt.Dimension(842, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Desarrollado por la ONG \"Agua Limpia\"");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(816, 816, 816))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(41, 41, 41))
        );

        ContenedorBody.add(footer, java.awt.BorderLayout.CENTER);

        getContentPane().add(ContenedorBody, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JPanel ContMenu;
    private javax.swing.JPanel ContenedorBody;
    private javax.swing.JPanel ContenedorHeader;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Nav;
    private javax.swing.JPanel Titulo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPartidas;
    private javax.swing.JButton btnPlanillas;
    private javax.swing.JButton btnPresupuestos;
    private javax.swing.JButton btnProyectos;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel headerLogoNombre;
    private javax.swing.JPanel headerUsuarioSesion;
    private javax.swing.JPanel iconUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMisPreferencias;
    private javax.swing.JPanel nameUser;
    private javax.swing.JPanel perfilUser;
    private javax.swing.JPanel preferencias;
    // End of variables declaration//GEN-END:variables
}
