package interfaz;

import clases.ClsDatabase;

/**
 *
 * @author MK
 */
public class frmPrincipal extends javax.swing.JFrame {

    private ClsDatabase bd;

    /**
     * Creates new form frmPrincipal
     *
     * @param baseDatabased
     */
    public frmPrincipal(ClsDatabase baseDatabased) {
        this.bd = baseDatabased;
        initComponents();
        this.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);//estado maximizado de la ventana
        this.setLocationRelativeTo(null);//Centramos la ventana
    }

    public frmPrincipal() {
        initComponents();
        this.setExtendedState(frmPrincipal.MAXIMIZED_BOTH);//estado maximizado de la ventana
        this.setLocationRelativeTo(null);//Centramos la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo1 = new util.PanelFondo();
        labelTitle1 = new util.LabelTitle();
        blackTabbedPane2 = new util.BlackTabbedPane();
        panelDefault4 = new util.PanelDefault();
        panelDefault5 = new util.PanelDefault();
        panelDefault6 = new util.PanelDefault();
        panelDefault7 = new util.PanelDefault();
        panelDefault8 = new util.PanelDefault();
        panelDefault9 = new util.PanelDefault();
        panelDefault10 = new util.PanelDefault();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitle1.setText("Sistema de Costos de Agua y Saneamiento [SICAS v0.6]");

        blackTabbedPane2.setTabSelectedColor(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout panelDefault4Layout = new javax.swing.GroupLayout(panelDefault4);
        panelDefault4.setLayout(panelDefault4Layout);
        panelDefault4Layout.setHorizontalGroup(
            panelDefault4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault4Layout.setVerticalGroup(
            panelDefault4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Usuarios", panelDefault4);

        javax.swing.GroupLayout panelDefault5Layout = new javax.swing.GroupLayout(panelDefault5);
        panelDefault5.setLayout(panelDefault5Layout);
        panelDefault5Layout.setHorizontalGroup(
            panelDefault5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault5Layout.setVerticalGroup(
            panelDefault5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Insumos", panelDefault5);

        javax.swing.GroupLayout panelDefault6Layout = new javax.swing.GroupLayout(panelDefault6);
        panelDefault6.setLayout(panelDefault6Layout);
        panelDefault6Layout.setHorizontalGroup(
            panelDefault6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault6Layout.setVerticalGroup(
            panelDefault6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Partidas", panelDefault6);

        javax.swing.GroupLayout panelDefault7Layout = new javax.swing.GroupLayout(panelDefault7);
        panelDefault7.setLayout(panelDefault7Layout);
        panelDefault7Layout.setHorizontalGroup(
            panelDefault7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault7Layout.setVerticalGroup(
            panelDefault7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Plantillas", panelDefault7);

        javax.swing.GroupLayout panelDefault8Layout = new javax.swing.GroupLayout(panelDefault8);
        panelDefault8.setLayout(panelDefault8Layout);
        panelDefault8Layout.setHorizontalGroup(
            panelDefault8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault8Layout.setVerticalGroup(
            panelDefault8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Proyectos", panelDefault8);

        javax.swing.GroupLayout panelDefault9Layout = new javax.swing.GroupLayout(panelDefault9);
        panelDefault9.setLayout(panelDefault9Layout);
        panelDefault9Layout.setHorizontalGroup(
            panelDefault9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault9Layout.setVerticalGroup(
            panelDefault9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Presupuestos", panelDefault9);

        javax.swing.GroupLayout panelDefault10Layout = new javax.swing.GroupLayout(panelDefault10);
        panelDefault10.setLayout(panelDefault10Layout);
        panelDefault10Layout.setHorizontalGroup(
            panelDefault10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        panelDefault10Layout.setVerticalGroup(
            panelDefault10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        blackTabbedPane2.addTab("Configuración", panelDefault10);

        javax.swing.GroupLayout panelFondo1Layout = new javax.swing.GroupLayout(panelFondo1);
        panelFondo1.setLayout(panelFondo1Layout);
        panelFondo1Layout.setHorizontalGroup(
            panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondo1Layout.createSequentialGroup()
                        .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 295, Short.MAX_VALUE))
                    .addComponent(blackTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFondo1Layout.setVerticalGroup(
            panelFondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(blackTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelFondo1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private util.BlackTabbedPane blackTabbedPane2;
    private util.LabelTitle labelTitle1;
    private util.PanelDefault panelDefault10;
    private util.PanelDefault panelDefault4;
    private util.PanelDefault panelDefault5;
    private util.PanelDefault panelDefault6;
    private util.PanelDefault panelDefault7;
    private util.PanelDefault panelDefault8;
    private util.PanelDefault panelDefault9;
    private util.PanelFondo panelFondo1;
    // End of variables declaration//GEN-END:variables
}
